version: '3.7'

services:
  postgres-db:
    image: postgres:latest
    container_name: pg-db
    ports:
      - $POSTGRES_LOCAL_PORT:5432
    env_file:
      - .env
    volumes:
      - ./.pgdata/:/var/lib/postgresql/data
    
