version: '3.7'

services:
  postgres-db:
    image: postgres:latest
    container_name: pg-db
    hostname: pg-db
    ports:
      - $POSTGRES_LOCAL_PORT:5432
    env_file:
      - .env
    volumes:
      - ./.pgdata/:/var/lib/postgresql/data
    
  redis:
    image: redis:alpine
    container_name: redis-db
    hostname: redis-db
    ports:
      - $REDIS_PORT:6379
    volumes:
      - ./.redis/redis-data:/var/lib/redis
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    command: redis-server --requirepass $REDIS_PASSWORD
